name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Access
          token: ${{ secrets.METRICS_TOKEN }}

          # Base options
          user: kikui
          filename: metrics.svg
          template: classic
          base: header, activity, community, metadata
          config_timezone: Europe/Paris
          base_hireable: yes
          repositories_affiliations: owner, collaborator, organization_member

          # Pugin Options
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
